### ISSUE TITLE
heatware.py crashing upon launch

### ISSUE THREAD

**Issue by thelectronicnub** [thelectronicnub/mechkbot#3]
When running heatware.py, the error 

'File "heatware.py", line 55
    if str(reply.author.name) == username;
                                         ^
SyntaxError: invalid syntax'

is thrown, and exits immediately.

**Comment by Chankster** [comment]
Wait until I'm actually done please.

**Comment by thelectronicnub** [comment]
just making sure you were aware of the issues, sorry. let me know if there's anything you need me to test, tand thanks for doing this
